### ISSUE TITLE
array vs object

### ISSUE THREAD

**Issue by Gideon877** [codex-academy/api-with-psql-workshop#1]
@avermeulen the **response.body.data** on my test returns an array instead of an object. for the test to pass I have to change it to *response.body.data[0].gender*

`https://github.com/codex-academy/api-with-psql-workshop/blob/main/test/test.api.js#L105`

**Comment by avermeulen** [comment]
Make sure to use `oneOrNone` in PgPromise.
And not `manyOrNone` or any other method that returns a list.

@Gideon877

**Comment by Gideon877** [comment]
Noted, it worked liked magic
